### ISSUE TITLE
Security: Auditing Profile reconciliation between ROKS and Hypershift

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#1040]
The audit Policies deployed by Hypershift and what are currently offered in ROKS toolkit differs. Here are the current policies that are available:

default IBM Cloud policy
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: None
    userGroups: ["system:serviceaccounts:kube-system"]
  - level: None
    # Ingress controller reads `configmaps/ingress-uid` through the unsecured port.
    users: ["system:unsecured"]
    namespaces: ["kube-system"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["configmaps"]
  - level: None
    users: ["kubelet"] # legacy kubelet identity
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get", "patch"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["secrets"]
  - level: None
    users:
      - system:kube-controller-manager
      - system:kube-scheduler
      - system:serviceaccount:kube-system:endpoint-controller
    verbs: ["get", "update"]
    namespaces: ["kube-system"]
    resources:
      - group: "" # core
        resources: ["endpoints"]
  - level: None
    users: ["system:apiserver"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["namespaces"]
  # Don't log these read-only URLs.
  - level: None
    nonResourceURLs:
      - /healthz*
      - /version
      - /openapi/v2*
      - /readyz*
      - /livez*
  # Don't log events requests.
  - level: None
    resources:
      - group: "" # core
        resources: ["events"]
{% if openshift_version is version_compare('4.6', '>=') %}
      - group: "events.k8s.io"
        resources: ["events"]
{% endif %}
  # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
  # so only log at the Metadata level.
  - level: Metadata
    resources:
      - group: "" # core
        resources: ["secrets", "configmaps"]
      - group: authentication.k8s.io
        resources: ["tokenreviews"]
  # Log pvc/pv requests to capture volume details
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    verbs: ["create", "update", "patch"]
    resources:
    - group: "" #core
      resources: ["pods", "replicacontrollers", "container"]
    - group: "apps"
      resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    - group: "batch"
      resources: ["jobs", "cronjobs"]
    - group: "extensions" # necessary for pre-1.12 clusters
      resources: ["daemonsets", "deployments", "replicasets"]
  - level: RequestResponse
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: crd.projectcalico.org
  # Excludes the following apigroups from logs
  - level: None
    resources:
      - group: "apiregistration.k8s.io"
      - group: "coordination.k8s.io"
  # Get responses can be large; skip them.
  - level: Metadata
    verbs: ["create", "update", "delete", "patch"]
```

verbose policy:
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log pvc/pv requests to capture volume details
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    verbs: ["create", "update", "patch"]
    resources:
    - group: "" #core
      resources: ["pods", "replicacontrollers", "container"]
    - group: "apps"
      resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    - group: "batch"
      resources: ["jobs", "cronjobs"]
    - group: "extensions" # necessary for pre-1.12 clusters
      resources: ["daemonsets", "deployments", "replicasets"]
  - level: RequestResponse
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: crd.projectcalico.org
  # Log everything not covered above as Metadata.
  - level: Metadata
```

Posting the above for analysis..... And will use this to track if there are gaps between what is offered in hypershift versus ours that would result in auditing problems/problems for clients. If so: we would need to consider adding additional policies that we could specify for IBM Clusters.

**Comment by relyt0925** [comment]
There is the basis for us to be able to add more policies however the "enum" parameters come from upstream:
https://github.com/openshift/api/blob/b7057289fac81e08b06a564a0c724d1a4f3a783a/config/v1/types_apiserver.go#L77

https://github.com/openshift/hypershift/blob/626c61f6c8780244546256e80ef289e075fb0c6c/control-plane-operator/controllers/hostedcontrolplane/kas/auditcfg.go#L265

https://github.com/openshift/hypershift/blob/626c61f6c8780244546256e80ef289e075fb0c6c/control-plane-operator/controllers/hostedcontrolplane/kas/auditcfg.go#L77


The `writeRequestBodiesAuditPolicy` does appear to potentially cover all the rules in our policy with the:
https://github.com/openshift/hypershift/blob/626c61f6c8780244546256e80ef289e075fb0c6c/control-plane-operator/controllers/hostedcontrolplane/kas/auditcfg.go#L154

However: it does not have the level of filtering we have with our custom policies. We should see if that would potentially fit our use case as upstream Openshift does state that these are the only 3 policies available:
https://docs.openshift.com/container-platform/4.6/security/audit-log-policy-config.html

We would need to document the specific security needs from out perspective and have the redhat team review.

**Comment by relyt0925** [comment]
Upstream they also allow the ability to set custom rules:
https://docs.openshift.com/container-platform/4.9/security/audit-log-policy-config.html#configuring-audit-policy-custom_audit-log-policy-config

https://github.com/openshift/api/blob/b7057289fac81e08b06a564a0c724d1a4f3a783a/config/v1/types_apiserver.go#L115

That take precedence over the top level general profile. I believe if that was allowed we would have what we need to proceed forward with the custom profile. However: I am also not sure if we necessarily need that with the `WriteResponseBodies` profile. @rtheis will be able to provide more expert analysis on that specific situation though.

**Comment by relyt0925** [comment]
Looking further main gaps **Not Including filtering gaps** from the default policy is 
```
  # Log pvc/pv requests to capture volume details
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    verbs: ["create", "update", "patch"]
    resources:
    - group: "" #core
      resources: ["pods", "replicacontrollers", "container"]
    - group: "apps"
      resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    - group: "batch"
      resources: ["jobs", "cronjobs"]
    - group: "extensions" # necessary for pre-1.12 clusters
      resources: ["daemonsets", "deployments", "replicasets"]
  - level: RequestResponse
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: crd.projectcalico.org
```
