### ISSUE TITLE
Operations: priority class enhancements as node count changes

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#1041]
A recent addition to IBM Cloud actually modifies the priority class of the master control plane components to be higher if the customer is using more worker nodes in their cluster (and therefore spending more money on the offering).

The values are shown below
```
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-xs
    value: 1000000
    globalDefault: false
    description: "Used on master control plane resources for cruisers with 1-10 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-xs
    value: 1500000
    globalDefault: false
    description: "Used on master ETCD resources for cruisers with 1-10 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-s
    value: 2000000
    globalDefault: false
    description: "Used on master control plane resources for cruisers with 11-25 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-s
    value: 2500000
    globalDefault: false
    description: "Used on master ETCD resources for cruisers with 11-25 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-m
    value: 3000000
    globalDefault: false
    description: "Used on master control plane resources for cruisers with 26-50 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-m
    value: 3500000
    globalDefault: false
    description: "Used on master ETCD resources for cruisers with 26-50 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-l
    value: 4000000
    globalDefault: false
    description: "Used on master control plane resources for cruisers with 51-100 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-l
    value: 4500000
    globalDefault: false
    description: "Used on master ETCD resources for cruisers with 51-100 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-xl
    value: 5000000
    globalDefault: false
    description: "Used on master control plane resources for cruisers with 101-300 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-xl
    value: 5500000
    globalDefault: false
    description: "Used on master ETCD resources for cruisers with 101-300 workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-xxl
    value: 6000000
    globalDefault: false
    description: "Used on master control plane resources for cruisers with 300+ workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-xxl
    value: 6500000
    globalDefault: false
    description: "Used on master ETCD resources for cruisers with 300+ workers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-mcp-dedicated
    value: 7000000
    globalDefault: false
    description: "Used on master control plane resources for dedicated cruisers."
  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: cruiser-etcd-dedicated
    value: 7500000
    globalDefault: false
    description: "Used on master ETCD resources for dedicated cruisers."
```
