### ISSUE TITLE
Management cluster ingress ClusterOperator show error message because of private IngressController

### ISSUE THREAD

**Issue by sjenning** [openshift/hypershift#1103]
The private `IngressController` created by the CPO has the `spec.domain` set to `$clusterName.hypershift.local`.

```
spec:
  domain: sjenning-example.hypershift.local
```

```
# oc get dns.config.openshift.io cluster -oyaml
spec:
  baseDomain: sjenning.hypershift.sjennings.me
```

When DNS management is enabled on the cluster, the `ingress-operator` will attempt to create records for this name in the DNS zone configured in the DNS `cluster` config.  This fails because `hypershift.local` is not within the zone.  This results in the `IngressController` having `Available` condition status `False`. The `ingress` `ClusterOperator` shows an error message (though not being degraded).

```
# oc get ingresscontroller -n openshift-ingress-operator clusters-sjenning-example -oyaml
...
status:
  conditions:
  - lastTransitionTime: "2022-03-04T03:58:25Z"
    message: DNS management is supported and zones are specified in the cluster DNS
      config.
    reason: Normal
    status: "True"
    type: DNSManaged
  - lastTransitionTime: "2022-03-04T03:58:29Z"
    message: 'The record failed to provision in some zones: [{ map[Name:sjenning-vb8gp-int
      kubernetes.io/cluster/sjenning-vb8gp:owned]}]'
    reason: FailedZones
    status: "False"
    type: DNSReady
  - lastTransitionTime: "2022-03-04T03:59:00Z"
    message: 'One or more status conditions indicate unavailable: DNSReady=False (FailedZones:
      The record failed to provision in some zones: [{ map[Name:sjenning-vb8gp-int
      kubernetes.io/cluster/sjenning-vb8gp:owned]}])'
    reason: IngressControllerUnavailable
    status: "False"
    type: Available

# oc get clusteroperators ingress
NAME      VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
ingress   4.9.21    True        True          False      2d1h    Not all ingress controllers are available.
```
