### ISSUE TITLE
Deprecated global config can only be applied once

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1630]
With recent deprecation of HC's `spec.configuration.items[]` fields, https://github.com/openshift/hypershift/pull/1463, when existing HCs are patched with updates on those fields, the changes will never be applied. This means that this API only supports backward compatibility only on the initial apply.

In our scenario, we have HCs that may look like..
```
apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: "{{ cluster_id }}"
  namespace: "{{ hosted_clusters_namespace }}"
  labels:
    clusterid: "{{ cluster_id }}"
  annotations:
   ...
spec:
  configuration:
    items:
    - apiVersion: config.openshift.io/v1
      kind: FeatureGate
      metadata:
        creationTimestamp: null
      spec:
        customNoUpgrade:
          disabled:
          - ServiceLBNodePortControl
        featureSet: CustomNoUpgrade
...
```
.. when the managing HOs gets updated with the above PR's change and HC gets reconciled, this will get mutated it to..
```
apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: "{{ cluster_id }}"
  namespace: "{{ hosted_clusters_namespace }}"
  labels:
    clusterid: "{{ cluster_id }}"
  annotations:
   ...
spec:
  configuration:
    featureGate:
      customNoUpgrade:
        disabled:
        - ServiceLBNodePortControl
      featureSet: CustomNoUpgrade
...
```

Now, when we conduct any sort of patch updates on `spec.configuration.items[]`, it will never be honored and will continue to use the values that was present at the initial apply.

Note: For IBM Cloud, we have separate update cycles for the HO and its HCs, so we will need to make sure compatibility is not broken between the two, nor dependent on one another.
