### ISSUE TITLE
Upgrade path from 4.10 to 4.11 is broken with v1beta1 support

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1955]
We’re running into issues with upgrades paths from 4.10 --> 4.11 using HO that’s v1beta1 capable. And it looks like the contributing factor is the move of components (cluster-autoscaler, ignition-server, machine-approver) that’s HO-managed to CPO-managed. Here’s what we're observing:
- HO (with v1beta1) reconciles 4.10 HC
- HO lays down owner references to objects that looks like:
```
  ownerReferences:
  - apiVersion: hypershift.openshift.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: HostedControlPlane
    name: 4-10
    uid: 7f48a7b0-dfba-4b90-9d63-135d2f7129de
```
- 4.10 HC deploys out successfully
- Now upgrade HC to 4.11
- 4.11 CPO tries to take ownership of these components by updating the owner references (note the difference in apiVersion):
```
  ownerReferences:
  - apiVersion: hypershift.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: HostedControlPlane
    name: 4-10
    uid: 7f48a7b0-dfba-4b90-9d63-135d2f7129de
```
- ^ But this is not happening with this error:
```
failed to update control plane: failed to reconcile autoscaler: failed to reconcile autoscaler role: Role.rbac.authorization.k8s.io \"cluster-autoscaler-management\" is invalid: metadata.ownerReferences: Invalid value: []v1.OwnerReference{v1.OwnerReference{APIVersion:\"hypershift.openshift.io/v1beta1\", Kind:\"HostedControlPlane\", Name:\"4-10\", UID:\"7f48a7b0-dfba-4b90-9d63-135d2f7129de\", Controller:(*bool)(0xc04d5f89b9), BlockOwnerDeletion:(*bool)(0xc04d5f89ba)}, v1.OwnerReference{APIVersion:\"hypershift.openshift.io/v1alpha1\", Kind:\"HostedControlPlane\", Name:\"4-10\", UID:\"7f48a7b0-dfba-4b90-9d63-135d2f7129de\", Controller:(*bool)(0xc04d5f89bb), BlockOwnerDeletion:(*bool)(0xc04d5f89bc)}}: Only one reference can have Controller set to true. Found \"true\" in references for 4-10 and 4-10
```
- We were able to get around this manually by removing the v1beta1 owner reference - then CPO was able to lay down it’s v1alpha1 owner reference to proceed.
- ^ This leads us to think that the fact the owner references have differing apiVersion , that’s treated as an addition to the ownerReferences annotation rather than a replace, which is causing issues.
