### ISSUE TITLE
Missing permissions for service account "hypershift-addon-manager-sa"

### ISSUE THREAD

**Issue by nastacio** [openshift/hypershift#2069]
I am using OCP 4.12.0 and saw several messages in the hypershift logs about the service account `hypershift-addon-manager-sa` not having permissions to list pods and replicasets, so I needed to add the resources below in order to get `HypershiftDeployment` resources processed.

I did not need to do this back in November when I first experimented with Hypershift (using OCP 4.11 at the time.)
 
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: hypershift-role
  namespace: multicluster-engine
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: hypershift-role-binding
  namespace: multicluster-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hypershift-role
subjects:
  - kind: ServiceAccount
    name: hypershift-addon-manager-sa
    namespace: multicluster-engine
```
