### ISSUE TITLE
GA Operations: Upstream IBM alertmanager and prometheus config setup

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#241]
This item involves working with the redhat team to properly upstream the monitoring setup we use with Prometheus + AlertManager and Pagerduty to operate our management clusters. There is interest in the specific alerts we use for monitoring the health of master components/etcd/ general infra health (nodes not ready, etc).

IBM Specific alerts will be left out (things like monitoring of our master components, IBM Cloud specific API monitoring, etc)

Acceptance Criteria:
- [ ] Upstream/outline general monitoring architecture and specific configs IBM Cloud uses to monitor masters deployed in the management cluster

**Comment by relyt0925** [comment]
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    carrier_name: prod-lon04-carrier1
    carrier_type: hub
    crn_cname: bluemix
    crn_ctype: public
    crn_region: eu-gb
    crn_servicename: containers-kubernetes
    crn_version: v1
    tip_customer_impacting: "false"
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - armada-ops-alertmanager.monitoring:9093
rule_files:
- /alert-rules/*.rules.yml
scrape_configs:
- job_name: carrier-api-server-10.45.5.130
  honor_timestamps: true
  params:
    module:
    - https_masters
    target:
    - https://10.45.5.130:8443/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-etcd-server-10.45.5.130
  honor_timestamps: true
  params:
    module:
    - https_etcd
    target:
    - https://10.45.5.130:4001/health
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-scheduler-server-10.45.5.130
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.45.5.130:10251/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-scheduler-extender-10.45.5.130
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.45.5.130:9001/health
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-controller-manager-server-10.45.5.130
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.45.5.130:10252/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-node-exporter-server-10.45.5.130
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://10.45.5.130:9100/
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-node-exporter-server-metrics-10.45.5.130
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 25s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - 10.45.5.130:9100
- job_name: carrier-etcd-server-metrics-10.45.5.130
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  tls_config:
    ca_file: /etc/kubernetes/cert/ca.pem
    cert_file: /etc/kubernetes/cert/etcd.pem
    key_file: /etc/kubernetes/cert/etcd-key.pem
    insecure_skip_verify: false
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - 10.45.5.130:4001
- job_name: carrier-api-server-10.112.131.169
  honor_timestamps: true
  params:
    module:
    - https_masters
    target:
    - https://10.112.131.169:8443/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-etcd-server-10.112.131.169
  honor_timestamps: true
  params:
    module:
    - https_etcd
    target:
    - https://10.112.131.169:4001/health
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-scheduler-server-10.112.131.169
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.112.131.169:10251/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-scheduler-extender-10.112.131.169
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.112.131.169:9001/health
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-controller-manager-server-10.112.131.169
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.112.131.169:10252/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-node-exporter-server-10.112.131.169
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://10.112.131.169:9100/
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-node-exporter-server-metrics-10.112.131.169
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 25s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - 10.112.131.169:9100
- job_name: carrier-etcd-server-metrics-10.112.131.169
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  tls_config:
    ca_file: /etc/kubernetes/cert/ca.pem
    cert_file: /etc/kubernetes/cert/etcd.pem
    key_file: /etc/kubernetes/cert/etcd-key.pem
    insecure_skip_verify: false
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - 10.112.131.169:4001
- job_name: carrier-api-server-10.72.104.208
  honor_timestamps: true
  params:
    module:
    - https_masters
    target:
    - https://10.72.104.208:8443/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-etcd-server-10.72.104.208
  honor_timestamps: true
  params:
    module:
    - https_etcd
    target:
    - https://10.72.104.208:4001/health
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-scheduler-server-10.72.104.208
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.72.104.208:10251/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-scheduler-extender-10.72.104.208
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.72.104.208:9001/health
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-controller-manager-server-10.72.104.208
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - 10.72.104.208:10252/healthz
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-node-exporter-server-10.72.104.208
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://10.72.104.208:9100/
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: carrier-node-exporter-server-metrics-10.72.104.208
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 25s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - 10.72.104.208:9100
- job_name: carrier-etcd-server-metrics-10.72.104.208
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  tls_config:
    ca_file: /etc/kubernetes/cert/ca.pem
    cert_file: /etc/kubernetes/cert/etcd.pem
    key_file: /etc/kubernetes/cert/etcd-key.pem
    insecure_skip_verify: false
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - 10.72.104.208:4001
- job_name: master-private-endpoint-c1-1-1.private.eu-gb.containers.cloud.ibm.com
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://c1-1-1.private.eu-gb.containers.cloud.ibm.com:20000
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: master-private-endpoint-c1-2-1.private.eu-gb.containers.cloud.ibm.com
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://c1-2-1.private.eu-gb.containers.cloud.ibm.com:20000
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: master-private-endpoint-c1-3-1.private.eu-gb.containers.cloud.ibm.com
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://c1-3-1.private.eu-gb.containers.cloud.ibm.com:20000
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: master-private-endpoint-c1.private.eu-gb.containers.cloud.ibm.com
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - http://c1.private.eu-gb.containers.cloud.ibm.com:20000
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: master-private-endpoint-firstboot-private.eu-gb.containers.cloud.ibm.com
  honor_timestamps: true
  params:
    module:
    - http_2xx
    target:
    - https://private.eu-gb.containers.cloud.ibm.com/bootstrap/firstboot
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - armada-ops-blackbox-exporter.monitoring:9115
- job_name: kubernetes-cadvisor
  honor_timestamps: true
  scrape_interval: 3m
  scrape_timeout: 2m30s
  metrics_path: /metrics
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  follow_redirects: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (container_cpu_usage_seconds_total)|(container_fs_writes_bytes_total)|(container_fs_reads_bytes_total)|(container_cpu_user_seconds_total)|(container_last_seen)|(container_fs_writes_total)|(container_fs_reads_total)|(container_cpu_load_average_10s)|(container_spec_cpu_shares)|(container_network_udp_usage_total)|(container_memory_failures_total)|(container_network_tcp_usage_total)|(container_tasks_state)|(container_start_time_seconds)|(container_cpu_system_seconds_total)|(container_memory_swap)|(container_memory_rss)|(container_memory_failcnt)|(container_memory_cache)|(container_spec_cpu_period)|(container_spec_memory_swap_limit_bytes)|(container_cpu_system_seconds_total)
    replacement: $1
    action: drop
  kubernetes_sd_configs:
  - role: node
    follow_redirects: true
- job_name: kubernetes-apiservers
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;kubernetes;https
    replacement: $1
    action: keep
  - source_labels: [__address__]
    separator: ;
    regex: (.+):(.+)
    target_label: hostname
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - role: endpoints
    follow_redirects: true
- job_name: kubernetes-service-endpoints
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 25s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ([\d\.]+:15090)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    separator: ;
    regex: (https?)
    target_label: __scheme__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    separator: ;
    regex: (.+)(?::\d+);(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: hostname
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod_name
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (kube_pod_status_ready)|(kube_pod_status_scheduled)|(kube_pod_container_info)|(armada_bootstrap:playbook_durations_count)|(armada_bootstrap:playbook_durations_sum)|(prometheus_target_sync_length_seconds)
    replacement: $1
    action: drop
  - source_labels: [pod]
    separator: ;
    regex: etcd-(.*)-[^-]*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [cronjob]
    separator: ;
    regex: kubx-etcd-backup-(.*)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [job_name]
    separator: ;
    regex: kubx-etcd-backup-(.*)-[^-]*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [pod]
    separator: ;
    regex: master-(.*)-[^-]*-[^-]*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [deployment]
    separator: ;
    regex: master-(.*)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [pod]
    separator: ;
    regex: cluster-updater-(.+?)-.*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [deployment]
    separator: ;
    regex: cluster-updater-(.+?)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [pod]
    separator: ;
    regex: cluster-health-(.+?)-.*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [deployment]
    separator: ;
    regex: cluster-health-(.+?)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [namespace]
    separator: ;
    regex: master-(.*)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  kubernetes_sd_configs:
  - role: endpoints
    follow_redirects: true
- job_name: kubernetes-services
  honor_timestamps: true
  params:
    module:
    - http_2xx
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_probepath]
    separator: ;
    regex: (.+);(.*)
    target_label: __param_target
    replacement: ${1}/${2}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: armada-ops-blackbox-exporter.monitoring:9115
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_service_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service_name
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [pod]
    separator: ;
    regex: etcd-([^-]*)-[^-]*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [cronjob]
    separator: ;
    regex: kubx-etcd-backup-(.*)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [job_name]
    separator: ;
    regex: kubx-etcd-backup-(.*)-[^-]*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [pod]
    separator: ;
    regex: master-(.*)-[^-]*-[^-]*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [deployment]
    separator: ;
    regex: master-(.*)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [pod]
    separator: ;
    regex: cluster-updater-(.+?)-.*
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [deployment]
    separator: ;
    regex: cluster-updater-(.+?)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  - source_labels: [namespace]
    separator: ;
    regex: master-(.*)
    target_label: cluster_id
    replacement: ${1}
    action: replace
  kubernetes_sd_configs:
  - role: service
    follow_redirects: true
- job_name: kubernetes-pods
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ([\d\.]+:15090)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([\d\.]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: ${1}:${2}
    action: replace
  - separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_pod_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_host_ip]
    separator: ;
    regex: (.*)
    target_label: hostname
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_app]
    separator: ;
    regex: (.*)
    target_label: service_name
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - role: pod
    follow_redirects: true
```
