### ISSUE TITLE
Specifying ovnkube-master-external NodePorts in HostedCluster

### ISSUE THREAD

**Issue by KiqoCode** [openshift/hypershift#2954]
Hi,

Is it possible specifying the NodePort of the ovnkube-master-external service in the HostedCluster object?
We are in a disconnected, locked down environment were we have to "hard code" each port that should be needed. 
We have noticed some issues were ovnkube-master-external service gets recreated with different ports each time, which makes the spoke control plane fail. 

We specified all other ports like this:
```
  services:
  - service: APIServer
    servicePublishingStrategy:
      nodePort:
        address: ******************
        port: 30474
      type: NodePort
  - service: OAuthServer
    servicePublishingStrategy:
      nodePort:
        address: ******************
        port: 30475
      type: NodePort
  - service: OIDC
    servicePublishingStrategy:
      nodePort:
        address: ******************
        port: 30476
      type: None
  - service: Konnectivity
    servicePublishingStrategy:
      nodePort:
        address: ******************
        port: 30477
      type: NodePort
  - service: Ignition
    servicePublishingStrategy:
      nodePort:
        address: ******************
        port: 30478
      type: NodePort
  - service: OVNSbDb
    servicePublishingStrategy:
      nodePort:
        address: ******************
        port: 30479
      type: NodePort
```

But have not found any examples of how to define these ports manually?
`clusters-test                                   ovnkube-master-external                                           NodePort       172.30.149.17    <none>                                                                              9641:30789/TCP,9642:32587/TCP                              4h38m`
