### ISSUE TITLE
How to define trusted TLS certs for the componentRoutes on the management cluster

### ISSUE THREAD

**Issue by callum-stakater** [openshift/hypershift#3378]
there doesnt seem to be any documentation about how to setup hostedclusters with valid certificates for all the endpoints

we have been able to get valid certs for the hostedclusters API and the routes served inside the hostedcluster (such as console) but for the `componentRoutes` on the parent cluster we are struggling 

in the hostedcluster CRD it mentions that specifying `spec.configuration.ingress.componentRoutes.servingCertKeyPairSecret.name` pointing to a certificate in the `openshift-config` namespace is the way to do it but doing so like:

```
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  creationTimestamp: null
  name: c-shift
  namespace: c-shift
spec:
  autoscaling: {}
  controllerAvailabilityPolicy: HighlyAvailable
  configuration:
    ingress:
      componentRoutes:
      - hostname: ignition-server-c-shift.hypershift.us.kubeapp.cloud
        name: ignition-server
        namespace: c-shift-c-shift
        servingCertKeyPairSecret:
          name: cluster-certificate
      - hostname: konnectivity-server-c-shift-c-shift.apps.hypershift.us.kubeapp.cloud
        name: konnectivity-server
        namespace: c-shift-c-shift
        servingCertKeyPairSecret:
          name: cluster-certificate
      - hostname: oauth-c-shift-c-shift.apps.hypershift.us.kubeapp.cloud
        name: oauth
        namespace: c-shift-c-shift
        servingCertKeyPairSecret:
          name: cluster-certificate
```

results in the hosted cluster failing to deploy with error:

`failed to get referenced secret c-shift/cluster-certificate: Secret "cluster-certificate" not found`

if we copy the secret to the `c-shift` namespace the hostedcluster does come up successfully but when users of the hostedcluster are redirected to the `oauth` route (which is hosted on the management cluster and runs in `passthrough` mode the cert is always the auto generated selfsigned cert and is untrusted

**Comment by callum-stakater** [comment]
here is an extract from the CRD i mention for reference:

```
componentRoutes:
  description: "componentRoutes is an optional list of routes
    that are managed by OpenShift components that a cluster-admin
    is able to configure the hostname and serving certificate
    for. The namespace and name of each route in this list should
    match an existing entry in the status.componentRoutes list.
    \n To determine the set of configurable Routes, look at
    namespace and name of entries in the .status.componentRoutes
    list, where participating operators write the status of
    configurable routes."
  items:
    description: ComponentRouteSpec allows for configuration
      of a route's hostname and serving certificate.
    properties:
      hostname:
        description: hostname is the hostname that should be
          used by the route.
        pattern: ^([a-zA-Z0-9\p{S}\p{L}]((-?[a-zA-Z0-9\p{S}\p{L}]{0,62})?)|([a-zA-Z0-9\p{S}\p{L}](([a-zA-Z0-9-\p{S}\p{L}]{0,61}[a-zA-Z0-9\p{S}\p{L}])?)(\.)){1,}([a-zA-Z\p{L}]){2,63})$|^(([a-z0-9][-a-z0-9]{0,61}[a-z0-9]|[a-z0-9]{1,63})[\.]){0,}([a-z0-9][-a-z0-9]{0,61}[a-z0-9]|[a-z0-9]{1,63})$
        type: string
      name:
        description: "name is the logical name of the route
          to customize. \n The namespace and name of this componentRoute
          must match a corresponding entry in the list of status.componentRoutes
          if the route is to be customized."
        maxLength: 256
        minLength: 1
        type: string
      namespace:
        description: "namespace is the namespace of the route
          to customize. \n The namespace and name of this componentRoute
          must match a corresponding entry in the list of status.componentRoutes
          if the route is to be customized."
        maxLength: 63
        minLength: 1
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
        type: string
      servingCertKeyPairSecret:
        description: servingCertKeyPairSecret is a reference
          to a secret of type `kubernetes.io/tls` in the openshift-config
          namespace. The serving cert/key pair must match and
          will be used by the operator to fulfill the intent
          of serving with this name. If the custom hostname
          uses the default routing suffix of the cluster, the
          Secret specification for a serving certificate will
          not be needed.
        properties:
          name:
            description: name is the metadata.name of the referenced
              secret
            type: string
        required:
        - name
        type: object
    required:
    - hostname
    - name
    - namespace
```

**Comment by pstefka** [comment]
For Openshift 4.17 and the oauth service the solution was rather trivial, although not very nice (don't blame the messenger 😅) = add the oauth endpoint SAN (e.g. oauth-c-shift-c-shift.apps.hypershift.us.kubeapp.cloud) to the kube-apiserver certificate TLS secret mentioned in the hostedcluster.spec.configuration.apiServer.servingCerts.namedCertificates[].servingCertificate.name

**Comment by dwrolvink** [comment]
For us `hostedcluster.spec.configuration.apiServer` is not filled in. Not sure how this would affect the OAuth server?

We're having exactly the same issue on Openshift 4.18. We can configure `.spec.configuration.ingress.componentRoutes(name: oauth-openshift).servingCertKeyPairSecret` but the pods will keep using the `oauth-server-crt` secret, and the route remains on passthrough. Just getting the route to use reencrypt should already fix this for us as far as I can tell, as our default ingress cert is configured, but I cannot find how to enable that.

---

Btw, there is this item for Openshift, which is still open: https://access.redhat.com/solutions/7115668

---

Furthermore, the [api spec](https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/config_apis/ingress-config-openshift-io-v1#spec-15) says:

> To determine the set of configurable Routes, look at namespace and name of entries in the .status.componentRoutes list, where participating operators write the status of configurable routes.

But running ` oc get ingresses.config.openshift.io cluster -o yaml` in the child cluster does not show any componentroutes in the status field (it does for the ACM cluster, but just the ingress for the ACM cluster itself).

Suggesting this way of configuring would not work at all

---

ps. I tried pstefka's suggestion using:
``` yaml
    apiServer:
      servingCerts:
        namedCertificates:
        - names:
          - oauth-clusters-<cluster>.<acm domain>
          servingCertificate:
            name: default-ingress
```
This is also applied happily without any further effect as far as I can tell.

ps2. A couple hours later I noticed my open window had reloaded, and **now it works.** Looking at the pods, the kubeapi pods in the ACM cluster just had taken a bit longer to restart. This is the full `spec.configuration` block for the hostedcluster (note that the componentRoutes could be deleted as this block did nothing):

``` yaml
spec:
  configuration:
    apiServer:
      audit:
        profile: Default
      servingCerts:
        namedCertificates:
        - names:
          - oauth-clusters-<clustername>.<acm domain>
          servingCertificate:
            name: default-ingress
```

ps3. I was still wondering why altering the kubeapiserver did anything

Looking at the api pod, I saw that the default-ingress cert was now mounted under `named-cert-1`:
```
$  oc get pod kube-apiserver-74d97874fb-7czjh -o yaml | grep -B 3 -- default-ingress

  - name: named-cert-1
    secret:
      defaultMode: 416
      secretName: default-ingress
```

Looking at all the relevant secrets now:
```
$  oc get secret -A | grep default-ingress

openshift-ingress  default-ingress  kubernetes.io/tls                     2      27h      # main ingress cert
clusters           default-ingress  kubernetes.io/tls                     2      4h55m    # copy I made so that the hostedcluster can reach it
clusters-hcp07     default-ingress  kubernetes.io/tls                     2      6m47s    # this one is autogenerated, and returns if I delete it
```

And yes, looking at the oauth pod, the same secret is mounted, and specifically at this path:
``` 
$  oc get pod oauth-openshift-77b488657f-bqsql -o yaml | grep named-cert-1 -B 1

    - mountPath: /etc/kubernetes/certs/named-1
      name: named-cert-1
```

So adding that block to the kubeapi server config does something that affected the oauth pods as well. Curiously, of all the control plane pods, these are also the only that receive this mount:
``` 
$  for pod in $(oc get pods -o name); do res="$(oc get $pod -o yaml | grep -- default-ingress)"; [[ -n "$res" ]] && echo -e "-- $pod\n$res"; done
-- pod/kube-apiserver-74d97874fb-7czjh
      secretName: default-ingress
-- pod/kube-apiserver-74d97874fb-9njmt
      secretName: default-ingress
-- pod/kube-apiserver-74d97874fb-px97w
      secretName: default-ingress
-- pod/oauth-openshift-77b488657f-bqsql
      secretName: default-ingress
-- pod/oauth-openshift-77b488657f-p2kbl
      secretName: default-ingress
```

Thanks a lot @pstefka !
Will ask our Red Hat representatives what's in the works to get this sorted or at least better documented.

----

ps.4 Deploying a new cluster with these settings already in the HostedCluster, the deployment hangs on creating the VMs:

``` 
oc -n clusters describe nodepool hcp05-pool

Events:
  Type     Reason          Age                    From                 Message
  ----     ------          ----                   ----                 -------
  Warning  ReconcileError  3m21s (x9 over 58m)    nodepool-controller  failed to generate HAProxy raw config: failed to generate haproxy ignition config: waiting for missing componenent
  Warning  ReconcileError  3m7s (x24 over 58m)    nodepool-controller  error getting token: failed to generate HAProxy raw config: failed to generate haproxy ignition config: waiting for missing componenent
```

The fix for this is to create the cert secret in BOTH the `clusters` AND the `clusters-<clustername>` namespaces. 

If it is missing in the first you will get a clear error when running e.g. `oc describe hostedcluster hcp07 | grep ReconciliationSucceeded -B 4`, if it is missing in the second namespace, it will just hang like shown above.
