### ISSUE TITLE
Openshift APIServer Proxy integration for in cluster/on prem registries and webhook validation

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#341]
Currently the Openshift API Server has no access to in cluster webhooks. This means if someone creates a webhook on a resource processed by the openshift apiserver the openshift apiserver will crash.

This will be fixed by proxying traffic through konnectivity into the cluster to be able to reach the webhooks

**Comment by mihalysz22** [comment]
Nginx as a sidecar proxy to the OpenShift API Server can proxy the requests to the konnectivity-server with the following L4 tunneling configuration:
```
events {}
stream {
    upstream konnectivity-server.master-${clusterid} {
        server konnectivity-server.master-${clusterid}:8090;
   }

    server {
        listen     10081;
        proxy_pass konnectivity-server.master-${clusterid};
        proxy_ssl  on;

        proxy_ssl_certificate         /etc/myssl/konnectivity-client.pem;
        proxy_ssl_certificate_key     /etc/myssl/konnectivity-client-key.pem;
        proxy_ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
        proxy_ssl_ciphers             HIGH:!aNULL:!MD5;
        proxy_ssl_trusted_certificate /etc/myssl/ca.crt;

        proxy_ssl_verify        on;
        proxy_ssl_verify_depth  2;
        proxy_ssl_session_reuse on;
    }
}
```
Here - for this poc - I've used the kube-apiserver's existing cert and key from the kube-apiserver secret.

And then redirecting the openshift-apiserver container's traffic:
```
        env:
        - name: HTTP_PROXY
          value: http://127.0.0.1:10081
        - name: HTTPS_PROXY
          value: http://127.0.0.1:10081
        - name: NO_PROXY
          value: kube-apiserver
```

It also worth noting the konnectivity-agent's `dnsPolicy` must be set `ClusterFirst` (this is the default) so agents can resolve the webhook service's hostname.
