### ISSUE TITLE
use HTTPS on ignition download from ignition server (FedRamp reqs for encrypted traffic)

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#354]
since this traffic contains  customer certs we need the traffic to be encrypted on the download from the pod that is ran: right now it uses the http endpoint

**Comment by relyt0925** [comment]
One potential solution to discuss:
Let's use a headless service for the machine config pod:
Then we can sign the cert with a wildcard on the headless service which will allow us to properly do TLS downloads.

Headless service domain format is
PODID.HEADLESS_SERVICE_NAME.NAMESPACE.svc.cluster.local

**Comment by relyt0925** [comment]
Current strategy: have ignition bootstrapper run over localhost and update configs all local to the pod instead of having to go over the network

**Comment by relyt0925** [comment]
General code path is here:
https://github.com/openshift/hypershift/blob/main/ignition-server/controllers/machineconfigserver_ignitionprovider.go#L64

**Comment by relyt0925** [comment]
example ibm cloud node pool 
```
apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: "tyler21-pool1"
  namespace: master
  labels:
    clusterid: "tyler21"
spec:
  clusterName: "tyler21"
  nodeCount: 2
  nodePoolManagement:
    upgradeType: Replace
    recreate:
      strategy: OnDelete
  platform:
    type: IBMCloud
  release:
    image: registry.ng.bluemix.net/armada-master/ocp-release:4.8.0-fc.8-x86_64
```
