### ISSUE TITLE
Proposal: Enable multi-zonal control plane component spread by default

### ISSUE THREAD

**Issue by ironcladlou** [openshift/hypershift#369]
We anticipate multi-zonal spread of control plane components to be a common requirement (e.g. https://github.com/openshift/hypershift/issues/227).

One approach that we think may satisfy the majority use case is to define multi-zonal in terms of anti-affinity rules based on the `kubernetes.io/hostname` and `topology.kubernetes.io/zone` topology keys for pod anti-affinity. This proposal is to set default anti-affinity rules for control plane components deployments like:

```yaml
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: app
            operator: In
            values: [...]
      topologyKey: "kubernetes.io/hostname"
    - labelSelector:
        matchExpressions:
          - key: app
            operator: In
            values: [...]
      topologyKey: "topology.kubernetes.io/zone"
```

These defaults would apply regardless of HA mode on the hostedcluster and would ensure that basic multi-zone spreading is implemented by default. If this satisfies the known use cases, we don't need any generic configuration API for anti-affinity at this time.

TODO: Define the exhaustive list of control plane components which to which these defaults will be applied.
