### ISSUE TITLE
Proposal: Enable control plane node exclusivity through built-in well-known tolerations

### ISSUE THREAD

**Issue by ironcladlou** [openshift/hypershift#371]
We anticipate the need for users to dedicate nodes to control planes for various reasons (e.g. https://github.com/openshift/hypershift/issues/237 regarding noisy neighbors, resource requirements, etc.). One way we expect users to achieve node exclusivity is through the use of taints and tolerations.

This proposal is to bake in some default tolerations to each control plane component which define well-known/predictable values which can be leveraged by users to add corresponding taints to their nodes to achieve node exclusivity for any set of hosted control planes.

Each control plane component would have a default toleration set like:

```yaml
tolerations:
- key: "hypershift.openshift.io/control-plane"
  operator: "Equal"
  value: "true"
  effect: NoSchedule
- key: "hypershift.openshift.io/$cluster-id"
  operator: "Equal"
  value: "true"
  effect: NoSchedule
```

The idea being that the end user could taint nodes in such a way that the nodes are dedicated to hosted clusters generally, or any subset (1 or many) of hosted clusters based on their ID.

TODO: Decide what is the right value to use for the unique cluster ID (e.g. hostedcluster UUID, namespace+name tuple, etc.)
TODO: Define the exhaustive list of control plane components which to which these defaults will be applied.
