### ISSUE TITLE
Unable to Register New Nodes in HostedCluster When Adding API Server Certificate

### ISSUE THREAD

**Issue by alfredtm** [openshift/hypershift#3985]
Hello! When adding API server certificate to the HostedCluster

```
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: test
  namespace: test
spec:
  configuration:
    apiServer:
      servingCerts:
        namedCertificates:
        - servingCertificate:
            name: tls-secret
``` 
The bootstrap-kubeconfig is no longer trusted

``` 
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "root-ca")
``` 
This seems to be a issue when adding new nodes (using kubevirt) to the cluster. They dont register/show up on the HostedCluster. 

When not adding certificate to the apiServer the nodes register fine.
