### ISSUE TITLE
Multiple ssh keys not supported

### ISSUE THREAD

**Issue by sjenning** [openshift/hypershift#476]
If the `--ssh-key` file passed to `create cluster` contains more than one key, the node controller fails to create a valid `MachineConfig`
```
# oc get nodepool -n clusters example -oyaml
apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  ...
...
status:
  conditions:
...
  - lastTransitionTime: "2021-09-16T15:17:42Z"
    message: 'configmap "ignition-config-99-worker-ssh" failed validation: error decoding config: yaml: line 20: could not find expected '':'''
    observedGeneration: 4
    reason: ValidationFailed
    status: "False"
    type: ValidConfig
```
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata: 
  labels: 
    machineconfiguration.openshift.io/role: master
  name: 99-worker-ssh
spec: 
  config: 
    ignition: 
      version: "2.2.0"
    passwd: 
      users: 
        - 
          name: core
          sshAuthorizedKeys: 
            - |-
                ssh-rsa AAAA...
ssh-rsa AAAA... <-- not indented
```
fyi @enxebre
