### ISSUE TITLE
Support for ImageTagMirrorSet via ImageContentSource in HostedCluster

### ISSUE THREAD

**Issue by stianfro** [openshift/hypershift#5608]
It is currently possible to create a HostedCluster and specify [imageContentSources](https://hypershift-docs.netlify.app/reference/api/#hypershift.openshift.io/v1beta1.ImageContentSource) like this:

```yaml
spec:
  imageContentSources:
    - mirrors:
        - 'mirror.example.com'
      source: docker.io
```

Which results in a `ImageDigestMirrorSet` inside the cluster:

```
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  labels:
    hypershift.openshift.io/managed: 'true'
    machineconfiguration.openshift.io/role: worker
  name: cluster
spec:
  imageDigestMirrors:
    - mirrors:
        - 'mirror.example.com'
      source: docker.io
```

This again configures `/etc/containers/registries.conf` on the nodes in the cluster:

```
unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
short-name-mode = ""

[[registry]]
  prefix = ""
  location = "docker.io"

  [[registry.mirror]]
    location = "mirror.example.com"
    pull-from-mirror = "digest-only"
```

Howerer there does not seem to be a way to have a [`ImageTagMirrorSet`](https://docs.openshift.com/container-platform/4.17/openshift_images/image-configuration.html#images-configuration-registry-mirror-configuring_image-configuration) be created through this flow.

_There is also no way to create a mirror with [`pull-from-mirror = "all"`
](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md) as the setting but I imagine this is an opinionated thing in OpenShift itself._

From my testing it doesn't even seem like creating a `ImageTagMirrorSet` manually inside a hosted cluster has any effect, the mirrors specified are never added to `/etc/containers/registries.conf`.

Are there any plans for adding support for this? If there are no immediate plans, could someone point me in the right direction on where to start if it is possible to contribute to this? 🙂

**Comment by aushacker** [comment]
(HCP newb) I have a customer asking about this one. Is the workaround to get them to deploy using digests, rather than tag?

Also, should the HostedCluster schema be changed i.e. deprecate `imageContentSources` and add optional fields for `imageDigestMirrors` and `imageTagMirrors`?

**Comment by stianfro** [comment]
@aushacker I found that the easiest way currently is to create a machineconfig that configures registry directly.

Here is the butane file I used to generate the machineconfig:

```yaml
# 99-worker-registry-mirror.bu
variant: openshift
version: 4.17.0
metadata:
  name: 99-worker-registry-mirror 
  labels:
    machineconfiguration.openshift.io/role: worker 
storage:
  files:
  - path: /etc/containers/registries.conf.d/001-mirrors.conf
    mode: 0644 
    overwrite: true
    contents:
      inline: |
        [[registry]]
          location = "docker.io"
        
          [[registry.mirror]]
            location = "mirror.example.com:443"
            pull-from-mirror = "all"
```

After using butane on this to generate the machineconfig yaml it can then be put into a configmap:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: 99-worker-registry-mirror
data:
  config: |-
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: worker
      name: 99-worker-registry-mirror
    spec:
      config:
        ignition:
          version: 3.4.0
        storage:
          files:
            - contents:
                compression: gzip
                source: data:;base64,foo
              mode: 420
              overwrite: true
              path: /etc/containers/registries.conf.d/001-mirrors.conf
```

And the nodepool can then be configured to use that machineconfig:

```yaml
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: worker-pool-1
spec:
  config:
    - name: 99-worker-registry-mirror
```

In my case this is using kubevirt as the platform, so not sure how it would be with others but I imagine it would be quite similar.
