### ISSUE TITLE
spec.nodePoolManagement: Required value

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/hypershift#576]
Following this [How to add additional node pools to the example cluster](https://github.com/openshift/hypershift#how-to-add-additional-node-pools-to-the-example-cluster):
```yaml
[cloud-user@preserve-olm-env hypershift]$ cat nodepool.yaml 
apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  namespace: clusters
  name: example-extended
spec:
  clusterName: example
  nodeCount: 1
  platform:
    aws:
      instanceType: m5.large
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.9.0-x86_64
```
But, get the below errors:
```yaml
[cloud-user@preserve-olm-env hypershift]$ oc create -f nodepool.yaml
The NodePool "example-extended" is invalid: spec.nodePoolManagement: Required value

[cloud-user@preserve-olm-env hypershift]$ oc version
Client Version: 4.9.0-rc.7
Server Version: 4.10.0-0.nightly-2021-10-16-173656
Kubernetes Version: v1.22.1+9312243
```
